# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np

In [2]:
np.random.randint(0, 20, size = (4, 7))

array([[ 7, 16, 13, 14, 14, 12, 12],
       [17, 15,  2,  4,  3,  5, 13],
       [11, 14,  7,  4,  3, 12, 15],
       [14,  3,  5,  2,  4, 15, 12]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [3]:
np.random.randint(0, 10, size = (8, 10))

array([[5, 0, 4, 3, 4, 4, 4, 1, 0, 5],
       [6, 2, 5, 7, 4, 8, 5, 5, 3, 0],
       [6, 1, 1, 1, 8, 4, 7, 6, 3, 8],
       [6, 0, 8, 0, 9, 5, 5, 5, 7, 4],
       [1, 9, 3, 0, 4, 7, 9, 3, 0, 5],
       [4, 5, 1, 9, 4, 5, 7, 6, 2, 6],
       [0, 1, 5, 2, 9, 5, 9, 4, 6, 0],
       [5, 0, 8, 9, 4, 8, 5, 3, 6, 7]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [4]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

Первое

In [5]:
#orgArray = np.loadtxt("./data/minutes_n_ingredients.csv", dtype = {'names': ('id_row', 'minutes', 'ingriD'),
#                     'formats': ('i4', 'i4', 'i4')} , skiprows = 1, delimiter = ',')
orgArray = np.loadtxt("./data/minutes_n_ingredients.csv", dtype = 'int32', skiprows = 1, delimiter = ',')
#orgArray.shape
#np.sort(orgArray.view('i4,i4,i4'), order=['f0'], axis=0).view(np.int32)\
print(orgArray)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


Второе

In [6]:
chippedArray = np.delete(orgArray,0,1)
orgMed = np.median(chippedArray, axis = 0)
orgMed


array([40.,  9.])

In [7]:
orgMax = np.max(chippedArray, axis = 0)
orgMax

array([2147483647,         39], dtype=int32)

In [8]:
orgMin = np.min(chippedArray, axis = 0)
orgMin

array([0, 1], dtype=int32)

Третье

In [22]:
quant75 = np.quantile(chippedArray,0.75,axis = 0)
clippedArray = orgArray
clippedArray[:, 1] = np.clip(orgArray[:, 1], None, quant75[0])
clippedArray
#np.max(clippedArray, axis = 0)

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]], dtype=int32)

Четвертое

In [10]:
#np.min(np.where(clippedArray == 0, 1, clippedArray),axis = 0)
entDZero = clippedArray.shape[0] - np.count_nonzero(clippedArray[:, 1])
entDZero

479

In [11]:
nonZeroArray = np.where(clippedArray == 0, 1, clippedArray)
nonZeroArray

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]], dtype=int32)

Пятое

In [12]:
#unique pairs np.unique(nonZeroArray[:, 1:3].view('i4,i4')).shape
#np.unique(orgArray[:, 1:3].view('i4,i4')).shape
#nonZeroArray[:, 1:3].view('i4,i4')
uniqueIDA = np.unique(nonZeroArray[:, 0]).shape[0]
uniqueIDA

100000

Шестое

In [13]:
uniqueIngr = np.unique(nonZeroArray[:, 2])
uniqueIngr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39], dtype=int32)

In [14]:
uniqueIngrA = uniqueIngr.shape[0]
uniqueIngrA

37

Седьмое

In [15]:
sortedArray = np.sort(nonZeroArray.view('i4,i4,i4'), order=['f2'], axis=0).view(np.int32)
num5 = np.extract(sortedArray[:, 2] <= 5, sortedArray[:, 2]).shape[0]
inG5Array = sortedArray[0:num5]
inG5Array

array([[ 24802,     15,      1],
       [134711,     10,      1],
       [153034,     35,      1],
       ...,
       [536063,     35,      5],
       [536729,     10,      5],
       [537485,     45,      5]], dtype=int32)

Восьмое

In [16]:
effArray = nonZeroArray[:, 2]/nonZeroArray[:, 1]
effArray

array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
       0.21538462])

In [17]:
maxEff = np.max(effArray)
maxEff

24.0

Девятое

In [18]:
sortedByTimeArray = np.sort(nonZeroArray.view('i4,i4,i4'), order=['f1'], axis=0).view(np.int32)
top100TimeArray = sortedByTimeArray[sortedByTimeArray.shape[0]-100:sortedByTimeArray.shape[0]]
meanTop100 = np.mean(top100TimeArray[:, 2])
meanTop100

13.11

Десятое

In [20]:
indices = np.random.choice(orgArray.shape[0], size=10, replace=False)
print(orgArray[indices])


[[ 42428     65     11]
 [504498     65     12]
 [126307     60     15]
 [ 54169     40     10]
 [ 74573     10      6]
 [468204     25      7]
 [149471     65     15]
 [ 67538     60      9]
 [407964     65     14]
 [321982     65      8]]


Одиннадцатое

In [21]:
meanInG = np.mean(sortedArray[:, 2])
numMeanIng = np.extract(sortedArray[:, 2] < meanInG, sortedArray[:, 2]).shape[0]
percentMeanIng = numMeanIng/sortedArray.shape[0]*100
print(percentMeanIng,"%")

58.802 %


Двенадцатое

In [28]:
simple_recipe = np.zeros((orgArray.shape[0], orgArray.shape[1] + 1), dtype=np.int32)
simple_recipe[:, :-1] = orgArray
simple_recipe[:, -1] = ((orgArray[:, 1] <= 20) & (orgArray[:, 2] <= 5)).astype(np.int32)
simple_recipe

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]], dtype=int32)

Тринадцатое

In [29]:
simple_recipe_count = np.sum(simple_recipe[:, -1])
total_count = simple_recipe.shape[0]
simple_recipe_percent = simple_recipe_count / total_count * 100
print(f'Процент "простых" рецептов в датасете: {simple_recipe_percent:.2f}%')

Процент "простых" рецептов в датасете: 9.55%


Четырнадцатое

In [31]:
short_recipes = orgArray[orgArray[:, 1] < 10]
standard_recipes = orgArray[(orgArray[:, 1] >= 10) & (orgArray[:, 1] <= 20)]
long_recipes = orgArray[orgArray[:, 1] > 20]

# Выбираем максимальное количество рецептов из каждой группы
max_count = min(short_recipes.shape[0], standard_recipes.shape[0], long_recipes.shape[0])
short_recipes = short_recipes[:max_count]
standard_recipes = standard_recipes[:max_count]
long_recipes = long_recipes[:max_count]

# Создаем трехмерный массив
recipes = np.array([short_recipes, standard_recipes, long_recipes])

# Выводим форму полученного массива
print(f'Форма полученного массива: {recipes.shape}')

Форма полученного массива: (3, 7588, 3)
